export const SAMPLE_PINS = [
  {
    id: "1",
    restaurantName: "Dishoom",
    description:
      "The black daal is life-changing. Went for brunch and the bacon naan roll had us speechless. The chai is unreal too — proper spiced, not that syrup stuff.",
    cuisineTags: ["Indian"],
    rating: 5,
    likes: 22,
    username: "maya.k",
    area: "Shoreditch",
    createdAt: "2026-08-12",
  },
  {
    id: "2",
    restaurantName: "Padella",
    description:
      "Queued for 40 minutes but absolutely worth it. The pappardelle ragù is the best pasta I've had in London. Cash only-ish vibes, very Borough Market.",
    cuisineTags: ["Italian"],
    rating: 5,
    likes: 35,
    username: "tomfoodie",
    area: "Borough Market",
    createdAt: "2026-08-10",
  },
  {
    id: "3",
    restaurantName: "On The Bab",
    description:
      "Korean fried chicken that slaps. The gochujang glaze is sweet and spicy perfection. Cheap, fast, and the portions are generous.",
    cuisineTags: ["Korean"],
    rating: 4,
    likes: 18,
    username: "jess.eats",
    area: "Shoreditch",
    createdAt: "2026-08-09",
  },
  {
    id: "4",
    restaurantName: "Mangal 2",
    description:
      "Dalston's best-kept secret. The charcoal grill gives everything this incredible smoky depth. The lamb adana kebab is outrageous. Super affordable too.",
    cuisineTags: ["Turkish"],
    rating: 5,
    likes: 25,
    username: "ali.r",
    area: "Dalston",
    createdAt: "2026-08-08",
  },
  {
    id: "5",
    restaurantName: "Rosa's Thai Café",
    description:
      "Proper Thai food without the tourist markup. The pad kra pao is fiery and the green papaya salad is perfectly sour. Great vegan options too.",
    cuisineTags: ["Thai"],
    rating: 4,
    likes: 14,
    username: "samcooks",
    area: "Spitalfields",
    createdAt: "2026-08-07",
  },
  {
    id: "6",
    restaurantName: "Ottolenghi",
    description:
      "Every dish looks like a painting. The roasted aubergine with pomegranate is a flavour bomb. Pricey but you're paying for genuinely special food.",
    cuisineTags: ["Middle Eastern"],
    rating: 5,
    likes: 31,
    username: "nina.plates",
    area: "Islington",
    createdAt: "2026-08-06",
  },
  {
    id: "7",
    restaurantName: "Tacos Padre",
    description:
      "Best tacos in London, no debate. The al pastor is smoky and tangy, the corn tortillas are handmade, and the salsas have real kick. Borough Market gem.",
    cuisineTags: ["Mexican"],
    rating: 5,
    likes: 28,
    username: "marco.bites",
    area: "Borough Market",
    createdAt: "2026-08-05",
  },
  {
    id: "8",
    restaurantName: "Mildreds",
    description:
      "Even as a meat-eater I was blown away. The Sri Lankan curry is packed with flavour and they take allergies really seriously. Will be back.",
    cuisineTags: ["Vegetarian"],
    rating: 4,
    likes: 9,
    username: "priya.v",
    area: "Soho",
    createdAt: "2026-08-04",
  },
  {
    id: "9",
    restaurantName: "Jerk City",
    description:
      "The jerk chicken had me sweating in the best way. Perfectly charred, smoky, with rice and peas that taste like home. This is real Caribbean food.",
    cuisineTags: ["Caribbean"],
    rating: 5,
    likes: 20,
    username: "dwayne.eats",
    area: "Shoreditch",
    createdAt: "2026-08-03",
  },
];

export const CUISINE_FILTERS = [
  "All",
  "Indian",
  "Italian",
  "Korean",
  "Turkish",
  "Thai",
  "Middle Eastern",
  "Mexican",
  "Vegetarian",
  "Caribbean",
  "Japanese",
  "Chinese",
  "French",
  "Greek",
];
